// This file is @generated by prost-build.
/// 管理器请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManagerRequest {
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    #[prost(oneof = "manager_request::Payload", tags = "2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17")]
    pub payload: ::core::option::Option<manager_request::Payload>,
}
/// Nested message and enum types in `ManagerRequest`.
pub mod manager_request {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        CreateSession(super::CreateSession),
        /// ResizeWindow 已移除：由 Manager 直接处理（Worker 不持有 master_fd）
        #[prost(message, tag = "4")]
        KillSession(super::KillSession),
        #[prost(message, tag = "5")]
        ReadDir(super::ReadDir),
        #[prost(message, tag = "6")]
        ReadFile(super::ReadFile),
        #[prost(message, tag = "7")]
        WriteFile(super::WriteFile),
        #[prost(message, tag = "8")]
        ExecuteCommand(super::ExecuteCommand),
        #[prost(message, tag = "9")]
        GetSystemInfo(super::GetSystemInfo),
        #[prost(message, tag = "11")]
        Delete(super::Delete),
        #[prost(message, tag = "12")]
        Mkdir(super::Mkdir),
        #[prost(message, tag = "13")]
        Rename(super::Rename),
        #[prost(message, tag = "14")]
        Copy(super::Copy),
        #[prost(message, tag = "15")]
        Move(super::Move),
        #[prost(message, tag = "16")]
        FileExists(super::FileExists),
        #[prost(message, tag = "17")]
        ApplyDiff(super::ApplyDiff),
        /// 新增：优雅关闭请求
        #[prost(message, tag = "10")]
        GracefulShutdown(super::GracefulShutdown),
    }
}
/// Worker 响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerResponse {
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    #[prost(oneof = "worker_response::Payload", tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16")]
    pub payload: ::core::option::Option<worker_response::Payload>,
}
/// Nested message and enum types in `WorkerResponse`.
pub mod worker_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        SessionCreated(super::SessionCreated),
        #[prost(message, tag = "3")]
        DirListing(super::DirListing),
        #[prost(message, tag = "4")]
        FileContent(super::FileContent),
        #[prost(message, tag = "5")]
        WriteResult(super::WriteResult),
        #[prost(message, tag = "6")]
        CommandOutput(super::CommandOutput),
        #[prost(message, tag = "7")]
        SystemInfo(super::SystemInfo),
        #[prost(message, tag = "8")]
        Error(super::Error),
        #[prost(message, tag = "10")]
        DeleteResult(super::DeleteResult),
        #[prost(message, tag = "11")]
        MkdirResult(super::MkdirResult),
        #[prost(message, tag = "12")]
        RenameResult(super::RenameResult),
        #[prost(message, tag = "13")]
        CopyResult(super::CopyResult),
        #[prost(message, tag = "14")]
        MoveResult(super::MoveResult),
        #[prost(message, tag = "15")]
        FileExistsResult(super::FileExistsResult),
        #[prost(message, tag = "16")]
        ApplyDiffResult(super::ApplyDiffResult),
        /// 新增：关闭确认
        #[prost(message, tag = "9")]
        ShutdownAck(super::ShutdownAck),
    }
}
/// 错误响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSession {
    #[prost(uint32, tag = "1")]
    pub cols: u32,
    #[prost(uint32, tag = "2")]
    pub rows: u32,
    #[prost(string, tag = "3")]
    pub shell: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub working_directory: ::prost::alloc::string::String,
    /// 阶段 2 新增:用户隔离信息
    #[prost(uint32, tag = "5")]
    pub uid: u32,
    #[prost(uint32, tag = "6")]
    pub gid: u32,
    #[prost(string, tag = "7")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionCreated {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// abstract socket 名称（Manager 用于连接 Session 进程）
    #[prost(string, tag = "2")]
    pub socket_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResizeWindow {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KillSession {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadDir {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):UID
    #[prost(uint32, tag = "2")]
    pub uid: u32,
    /// 用户上下文(阶段 3 新增):GID
    #[prost(uint32, tag = "3")]
    pub gid: u32,
    /// 用户上下文(阶段 3 新增):用户名
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):家目录
    #[prost(string, tag = "5")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirListing {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<FileEntry>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_dir: bool,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(string, tag = "4")]
    pub mtime: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub permissions: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadFile {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):UID
    #[prost(uint32, tag = "2")]
    pub uid: u32,
    /// 用户上下文(阶段 3 新增):GID
    #[prost(uint32, tag = "3")]
    pub gid: u32,
    /// 用户上下文(阶段 3 新增):用户名
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):家目录
    #[prost(string, tag = "5")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileContent {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub mtime: u64,
    #[prost(uint64, tag = "4")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteFile {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// 用户上下文(阶段 3 新增):UID
    #[prost(uint32, tag = "3")]
    pub uid: u32,
    /// 用户上下文(阶段 3 新增):GID
    #[prost(uint32, tag = "4")]
    pub gid: u32,
    /// 用户上下文(阶段 3 新增):用户名
    #[prost(string, tag = "5")]
    pub username: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):家目录
    #[prost(string, tag = "6")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteResult {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub mtime: u64,
    #[prost(uint64, tag = "3")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Delete {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub uid: u32,
    #[prost(uint32, tag = "3")]
    pub gid: u32,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteResult {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mkdir {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub uid: u32,
    #[prost(uint32, tag = "3")]
    pub gid: u32,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MkdirResult {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Rename {
    #[prost(string, tag = "1")]
    pub old_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub uid: u32,
    #[prost(uint32, tag = "4")]
    pub gid: u32,
    #[prost(string, tag = "5")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameResult {
    #[prost(string, tag = "1")]
    pub old_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Copy {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub uid: u32,
    #[prost(uint32, tag = "4")]
    pub gid: u32,
    #[prost(string, tag = "5")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CopyResult {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Move {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub uid: u32,
    #[prost(uint32, tag = "4")]
    pub gid: u32,
    #[prost(string, tag = "5")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MoveResult {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileExists {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub uid: u32,
    #[prost(uint32, tag = "3")]
    pub gid: u32,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileExistsResult {
    #[prost(bool, tag = "1")]
    pub exists: bool,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(uint64, tag = "3")]
    pub mtime: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCommand {
    #[prost(string, tag = "1")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub working_directory: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):UID
    #[prost(uint32, tag = "4")]
    pub uid: u32,
    /// 用户上下文(阶段 3 新增):GID
    #[prost(uint32, tag = "5")]
    pub gid: u32,
    /// 用户上下文(阶段 3 新增):用户名
    #[prost(string, tag = "6")]
    pub username: ::prost::alloc::string::String,
    /// 用户上下文(阶段 3 新增):家目录
    #[prost(string, tag = "7")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandOutput {
    #[prost(bytes = "vec", tag = "1")]
    pub stdout: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub stderr: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub exit_code: i32,
}
/// 文件差异项
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileDiff {
    /// 差异类型: 0=insert, 1=delete, 2=replace
    #[prost(int32, tag = "1")]
    pub diff_type: i32,
    /// 行号(从 1 开始)
    #[prost(uint32, tag = "2")]
    pub line_number: u32,
    /// 原内容(replace/delete 时存在)
    #[prost(string, tag = "3")]
    pub old_content: ::prost::alloc::string::String,
    /// 新内容(replace/insert 时存在)
    #[prost(string, tag = "4")]
    pub new_content: ::prost::alloc::string::String,
}
/// 应用差异
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyDiff {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub base_mtime: u64,
    #[prost(message, repeated, tag = "3")]
    pub diffs: ::prost::alloc::vec::Vec<FileDiff>,
    #[prost(uint32, tag = "4")]
    pub uid: u32,
    #[prost(uint32, tag = "5")]
    pub gid: u32,
    #[prost(string, tag = "6")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub home_dir: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyDiffResult {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(uint64, tag = "3")]
    pub new_mtime: u64,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSystemInfo {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfo {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub os_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub uptime_secs: u64,
    #[prost(message, optional, tag = "6")]
    pub cpu: ::core::option::Option<CpuInfo>,
    #[prost(message, optional, tag = "7")]
    pub memory: ::core::option::Option<MemoryInfo>,
    #[prost(message, repeated, tag = "8")]
    pub disks: ::prost::alloc::vec::Vec<DiskInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CpuInfo {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cores: u32,
    #[prost(double, tag = "3")]
    pub usage_percent: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryInfo {
    #[prost(uint64, tag = "1")]
    pub total_bytes: u64,
    #[prost(uint64, tag = "2")]
    pub used_bytes: u64,
    #[prost(uint64, tag = "3")]
    pub available_bytes: u64,
    #[prost(double, tag = "4")]
    pub usage_percent: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskInfo {
    #[prost(string, tag = "1")]
    pub mount_point: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub filesystem: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub total_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub used_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub available_bytes: u64,
    #[prost(double, tag = "7")]
    pub usage_percent: f64,
}
/// Manager -> Worker 的优雅关闭请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GracefulShutdown {
    /// 宽限期（秒），超时后强制杀死
    #[prost(uint32, tag = "1")]
    pub grace_period_secs: u32,
    /// 是否进行状态迁移（Phase 4 暂不实现，始终为 false）
    #[prost(bool, tag = "2")]
    pub migrate_state: bool,
    /// 触发原因
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// Worker -> Manager 的关闭确认
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShutdownAck {
    /// 是否成功完成所有未决任务
    #[prost(bool, tag = "1")]
    pub all_tasks_completed: bool,
    /// 退出的会话数量（应为 0，不杀死 Sessions）
    #[prost(uint32, tag = "2")]
    pub sessions_count: u32,
}
/// Worker -> Manager 的状态迁移数据（Phase 4 暂不使用，预留扩展点）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerStateSnapshot {
    /// 待处理的请求 ID 列表
    #[prost(uint64, repeated, tag = "1")]
    pub pending_requests: ::prost::alloc::vec::Vec<u64>,
}
