// This file is @generated by prost-build.
/// 管理器请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ManagerRequest {
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    #[prost(oneof = "manager_request::Payload", tags = "2, 3, 4, 5, 6, 7, 8, 9")]
    pub payload: ::core::option::Option<manager_request::Payload>,
}
/// Nested message and enum types in `ManagerRequest`.
pub mod manager_request {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        CreateSession(super::CreateSession),
        #[prost(message, tag = "3")]
        ResizeWindow(super::ResizeWindow),
        #[prost(message, tag = "4")]
        KillSession(super::KillSession),
        #[prost(message, tag = "5")]
        ReadDir(super::ReadDir),
        #[prost(message, tag = "6")]
        ReadFile(super::ReadFile),
        #[prost(message, tag = "7")]
        WriteFile(super::WriteFile),
        #[prost(message, tag = "8")]
        ExecuteCommand(super::ExecuteCommand),
        #[prost(message, tag = "9")]
        GetSystemInfo(super::GetSystemInfo),
    }
}
/// Worker 响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerResponse {
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    #[prost(oneof = "worker_response::Payload", tags = "2, 3, 4, 5, 6, 7, 8")]
    pub payload: ::core::option::Option<worker_response::Payload>,
}
/// Nested message and enum types in `WorkerResponse`.
pub mod worker_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "2")]
        SessionCreated(super::SessionCreated),
        #[prost(message, tag = "3")]
        DirListing(super::DirListing),
        #[prost(message, tag = "4")]
        FileContent(super::FileContent),
        #[prost(message, tag = "5")]
        WriteResult(super::WriteResult),
        #[prost(message, tag = "6")]
        CommandOutput(super::CommandOutput),
        #[prost(message, tag = "7")]
        SystemInfo(super::SystemInfo),
        #[prost(message, tag = "8")]
        Error(super::Error),
    }
}
/// 错误响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSession {
    #[prost(uint32, tag = "1")]
    pub cols: u32,
    #[prost(uint32, tag = "2")]
    pub rows: u32,
    #[prost(string, tag = "3")]
    pub shell: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub working_directory: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionCreated {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResizeWindow {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KillSession {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadDir {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirListing {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<FileEntry>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_dir: bool,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(string, tag = "4")]
    pub mtime: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub permissions: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadFile {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileContent {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub mtime: u64,
    #[prost(uint64, tag = "4")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteFile {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteResult {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub mtime: u64,
    #[prost(uint64, tag = "3")]
    pub size: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCommand {
    #[prost(string, tag = "1")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub working_directory: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandOutput {
    #[prost(bytes = "vec", tag = "1")]
    pub stdout: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub stderr: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub exit_code: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSystemInfo {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfo {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub os_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub os_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub uptime_secs: u64,
    #[prost(message, optional, tag = "6")]
    pub cpu: ::core::option::Option<CpuInfo>,
    #[prost(message, optional, tag = "7")]
    pub memory: ::core::option::Option<MemoryInfo>,
    #[prost(message, repeated, tag = "8")]
    pub disks: ::prost::alloc::vec::Vec<DiskInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CpuInfo {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cores: u32,
    #[prost(double, tag = "3")]
    pub usage_percent: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryInfo {
    #[prost(uint64, tag = "1")]
    pub total_bytes: u64,
    #[prost(uint64, tag = "2")]
    pub used_bytes: u64,
    #[prost(uint64, tag = "3")]
    pub available_bytes: u64,
    #[prost(double, tag = "4")]
    pub usage_percent: f64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskInfo {
    #[prost(string, tag = "1")]
    pub mount_point: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub filesystem: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub total_bytes: u64,
    #[prost(uint64, tag = "5")]
    pub used_bytes: u64,
    #[prost(uint64, tag = "6")]
    pub available_bytes: u64,
    #[prost(double, tag = "7")]
    pub usage_percent: f64,
}
